id: A2BC6BB62
title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.905995
  last_modified_at: 2022-03-01 04:20:58.905998
