id: A2BC6BB62
title: Prayer for the Long Life of Khandro Tsering Chödrön
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.878722
  last_modified_at: 2022-03-01 04:20:58.878725
