id: A2BC6BB62
title: Long Life Prayer for Lodi Gyari Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.857246
  last_modified_at: 2022-03-01 04:20:58.857249
