id: A2BC6BB62
title: Long Life Prayer for Mayum Tsering Wangmo
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.859150
  last_modified_at: 2022-03-01 04:20:58.859153
