id: A2BC6BB62
title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.855753
  last_modified_at: 2022-03-01 04:20:58.855757
