id: A2BC6BB62
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.877291
  last_modified_at: 2022-03-01 04:20:58.877294
