id: A2BC6BB62
title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long Life
  of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.934180
  last_modified_at: 2022-03-01 04:20:58.934182
