id: A2BC6BB62
title: 'The Flower of Auspiciousness: A Prayer for the Long Life of Khenpo Khyenrab
  Chökyi Özer, Masterful Expositor of Scripture and Reasoning'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.915750
  last_modified_at: 2022-03-01 04:20:58.915755
