id: A2BC6BB62
title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness the Dalai
  Lama'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.930801
  last_modified_at: 2022-03-01 04:20:58.930805
