id: A2BC6BB62
title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong Trulshik
  Rinpoche, the Representative of Guru Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.852551
  last_modified_at: 2022-03-01 04:20:58.852554
