id: A2BC6BB62
title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth Incarnation
  of Terchen Chokgyur Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - es
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.938192
  last_modified_at: 2022-03-01 04:20:58.938195
