id: A2BC6BB62
title: Prayer for the Long Life of Pewar Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.890014
  last_modified_at: 2022-03-01 04:20:58.890016
