id: A2BC6BB62
title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives of the
  Supreme Holders of the Non-Sectarian Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.919645
  last_modified_at: 2022-03-01 04:20:58.919648
