id: A2BC6BB62
title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
  Khyentse, Thupten Chökyi Gyatso
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.842642
  last_modified_at: 2022-03-01 04:20:58.842676
