id: A2BC6BB62
title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku of Jamyang
  Khyentse, Thupten Chökyi Gyatso'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.939564
  last_modified_at: 2022-03-01 04:20:58.939566
