id: A2BC6BB62
title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the All-Knowing
  Paṇchen Rinpoche of Tsang'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.932493
  last_modified_at: 2022-03-01 04:20:58.932495
