id: A2BC6BB62
title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life of His
  Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One by Jamyang
  Khyentse Chökyi Lodrö'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.928090
  last_modified_at: 2022-03-01 04:20:58.928096
