id: A2BC6BB62
title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in the Succession
  of Lotus-Tongued Jamchen Tai Situ Incarnations'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.864387
  last_modified_at: 2022-03-01 04:20:58.864390
