id: A2BC6BB62
title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the Long
  Life of the Perfect Masters'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.940858
  last_modified_at: 2022-03-01 04:20:58.940861
