id: A2BC6BB62
title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.862916
  last_modified_at: 2022-03-01 04:20:58.862919
