id: A2BC6BB62
title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life of Ḍākinī
  Muntso Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.917162
  last_modified_at: 2022-03-01 04:20:58.917165
