id: A2BC6BB62
title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His Holiness
  the Dalai Lama'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.921498
  last_modified_at: 2022-03-01 04:20:58.921501
