id: A2BC6BB62
title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great Tertön
  Dudjom Jigdral Yeshe Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.907722
  last_modified_at: 2022-03-01 04:20:58.907725
