id: A2BC6BB62
title: General Long-Life Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:20:58.846923
  last_modified_at: 2022-03-01 04:20:58.846926
